# Site/SEO settings
port: 4001

email: noreply@example.com
baseurl: ""
permalink: /:year/:month/:day/:title/
google_analytics: 

name: Victor Li
title: Peaks and Valleys
description: >
  Victor's Outdoor Blog
url: http://peaksnvalleys.github.io

twitter_username: viclw17
default_img: /assets/images/favicon.ico

social:
  - name: twitter
    url: https://twitter.com/viclw17
  - name: instagram
    url: https://www.instagram.com/viclw17/
  # - name: linkedin
    # url: 
  # - name: github
    # url: 
  # - name: codepen
    # url: 

# Contact settings
contact_img: /assets/images/2022-08-07-brunswick/IMG_0394.JPG
formcarry: https://formcarry.com/s/HkIo0nMb7

# Disqus settings
# disqus: test-apkdzgmqhj

# MailChimp settings
mailchimp_action: https://samesies.us17.list-manage.com/subscribe/post-json?u=66ddf555dab480e6a8606430b&amp;id=89b3ee034f
mailchimp_input: b_66ddf555dab480e6a8606430b_89b3ee034f

# Author settings
author:
  - name: Victor Li
    bio: 
    url: 

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 12
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts: 
      - 'tag.html'
    title: 'The Barber Theme'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true

# Build settings
markdown: kramdown
plugins:
  # - jekyll-paginate-v2
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
sass:
    sass_dir: _assets/scss
    style: compressed
